// ═══════════════════════════════════════════════════════════════════════════════
// ESTILOS — TRACKER (compartidos entre GloomhavenTracker, InitiativeBar,
// NewEnemyInitPopup y SavedGamesScreen)
// ═══════════════════════════════════════════════════════════════════════════════
import { StyleSheet } from "react-native";
import { BG, CARD_BG, BORDER, TEXT, MUTED, ACCENT, DARK_BG } from "../data";

export const trackerStyles = StyleSheet.create({
  root:           { flex:1, backgroundColor:DARK_BG },
  header:         { backgroundColor:DARK_BG, flexDirection:"row", alignItems:"center", paddingHorizontal:4, paddingVertical:8 },
  headerRow1:     { flexDirection:"row", alignItems:"center", flex:1 },
  hIcon:          { fontSize:20, marginRight:6 },
  hTitle:         { fontSize:15, fontWeight:"bold", color:"#F5DEB3", letterSpacing:0 },
  hSub:           { fontSize:8, color:"#A0845C", letterSpacing:1 },
  initSec:        { backgroundColor:CARD_BG, borderBottomWidth:1, borderBottomColor:BORDER, paddingTop:8, paddingBottom:10 },
  initLbl:        { fontSize:9, color:MUTED, letterSpacing:1.5, fontWeight:"bold", textAlign:"center", marginBottom:6 },
  initRow:        { paddingHorizontal:12, gap:8, alignItems:"center" },
  initAvatar:     { alignItems:"center", width:52 },
  initImgWrap:    { width:44, height:44, borderRadius:22, overflow:"hidden", borderWidth:2,
                    borderColor:BORDER, backgroundColor:"#F0E6D0", justifyContent:"center", alignItems:"center" },
  initImgClass:   { borderColor:ACCENT },
  initImg:        { width:36, height:36 },
  initImgFull:    { width:44, height:44 },
  initAvatarLbl:  { fontSize:9, color:MUTED, marginTop:3, textAlign:"center", maxWidth:52 },
  initFloat:      { position:"absolute", zIndex:999 },
  initNumBadge:   { position:"absolute", top:0, left:0, right:0, bottom:0,
                    backgroundColor:"rgba(0,0,0,0.45)", borderRadius:22,
                    alignItems:"center", justifyContent:"center", elevation:4 },
  initNumTxt:     { color:"#fff", fontSize:20, fontWeight:"bold", lineHeight:24, textShadowColor:"#000",
                    textShadowOffset:{width:0,height:1}, textShadowRadius:3 },
  initNextBtn:    { width:48, height:60, backgroundColor:DARK_BG, borderLeftWidth:1, borderLeftColor:BORDER,
                    justifyContent:"center", alignItems:"center", flexShrink:0 },
  initFinBtn:     { backgroundColor:"#8B0000" },
  initInicioBtn:  { backgroundColor:"#3A5A2A" },
  initNextTxt:    { color:"#F5DEB3", fontSize:26, fontWeight:"bold", lineHeight:30 },
  initFinTxt:     { fontSize:13, fontWeight:"bold", letterSpacing:0.5 },
  initInicioTxt:  { fontSize:12, fontWeight:"bold", letterSpacing:0.5 },
  roundBtnRow:    { flexDirection:"row", gap:6 },
  endRoundBtn:    { flex:1, backgroundColor:"#5A2D0A", borderWidth:1, borderColor:"#A0845C", borderRadius:6, paddingVertical:9, alignItems:"center" },
  startRoundBtn:  { backgroundColor:"#2A4A1A" },
  endRoundBtnRight:{ },
  endRoundTxt:    { color:"#F5DEB3", fontSize:13, fontWeight:"bold", letterSpacing:1 },
  headerLand:     { backgroundColor:DARK_BG, flexDirection:"row", alignItems:"center", paddingHorizontal:4, paddingVertical:8, gap:6 },
  hIconSm:        { fontSize:16 },
  hTitleSm:       { fontSize:14, fontWeight:"bold", color:"#F5DEB3", letterSpacing:0, marginRight:4, flex:1 },
  endRoundBtnSm:  { backgroundColor:"#5A2D0A", borderWidth:1, borderColor:"#A0845C", borderRadius:6, paddingVertical:5, paddingHorizontal:10 },
  endRoundTxtSm:  { color:"#F5DEB3", fontSize:11, fontWeight:"bold" },
  levelRow:       { flexDirection:"row", alignItems:"center" },
  levelLbl:       { fontSize:10, color:"#A0845C", marginRight:3 },
  levelBtn:       { width:22, height:22, borderRadius:4, borderWidth:1, borderColor:"#5C3A1E", justifyContent:"center", alignItems:"center", marginLeft:2 },
  levelBtnOn:     { backgroundColor:ACCENT, borderColor:"#F5DEB3" },
  levelBtnTxt:    { fontSize:11, color:"#A0845C", fontWeight:"bold" },
  levelBtnTxtOn:  { color:"#F5DEB3" },
  addBar:         { backgroundColor:"#EDE4D0", borderBottomWidth:1, borderBottomColor:BORDER, paddingHorizontal:12, paddingVertical:8 },
  selectorBtn:    { flexDirection:"row", alignItems:"center", borderWidth:1, borderColor:BORDER, borderRadius:8, backgroundColor:CARD_BG, paddingHorizontal:10, paddingVertical:6 },
  selectorImgWrap:{ width:32, height:32, borderRadius:16, overflow:"hidden", borderWidth:1.5, borderColor:BORDER, marginRight:8, justifyContent:"center", alignItems:"center", backgroundColor:"#F0E6D0" },
  selectorImg:    { width:32, height:32, borderRadius:16 },
  selectorTxt:    { flex:1, fontSize:14, fontWeight:"bold", color:TEXT },
  selectorArrow:  { fontSize:16, color:MUTED, marginLeft:6 },
  addRow:         { flexDirection:"row", alignItems:"center", flexWrap:"wrap", gap:6 },
  variantBtn:     { width:50, paddingVertical:17, borderRadius:6, borderWidth:1.5, alignItems:"center" },
  variantBtnSm:   { paddingHorizontal:7, paddingVertical:5 },
  modalOverlay:   { flex:1, backgroundColor:"rgba(0,0,0,0.55)", justifyContent:"center", alignItems:"center" },
  modalBox:       { backgroundColor:CARD_BG, borderRadius:14, width:"88%", overflow:"hidden", borderWidth:2, borderColor:BORDER },
  modalHeader:    { flexDirection:"row", alignItems:"center", justifyContent:"space-between", paddingHorizontal:16, paddingVertical:12, borderBottomWidth:1, borderBottomColor:BORDER, backgroundColor:"#EDE4D0" },
  modalTitle:     { fontSize:15, fontWeight:"bold", color:TEXT },
  modalRow:       { flexDirection:"row", alignItems:"center", paddingHorizontal:14, paddingVertical:8, borderBottomWidth:1, borderBottomColor:"#EDE4D0" },
  modalRowOn:     { backgroundColor:"#FFF8E8" },
  modalImgWrap:   { width:36, height:36, borderRadius:18, overflow:"hidden", borderWidth:1.5, marginRight:12, justifyContent:"center", alignItems:"center", backgroundColor:"#F0E6D0" },
  modalImg:       { width:36, height:36, borderRadius:18 },
  modalRowTxt:    { fontSize:14, color:TEXT, flex:1 },
  addBarLand:     { backgroundColor:"#EDE4D0", borderBottomWidth:1, borderBottomColor:BORDER, paddingHorizontal:12, paddingVertical:6, flexDirection:"row", alignItems:"center" },
  addRowLand:     { flexDirection:"row", alignItems:"center", flexWrap:"wrap", gap:5 },
  playersBlock:   { flexDirection:"column", paddingRight:6, marginRight:2 },
  playersDivider: { height:1, backgroundColor:BORDER, marginVertical:3 },
  playersLbl:     { fontSize:9, color:MUTED, fontWeight:"bold", letterSpacing:0.5 },
  playersRow:     { flexDirection:"row", gap:3, alignItems:"center" },
  playersBtn:     { paddingHorizontal:9, paddingVertical:6, borderRadius:6, borderWidth:1, borderColor:BORDER },
  playersBtnOn:   { borderColor:"#8B0000", backgroundColor:"#FFE0E022" },
  playersTxt:     { fontSize:13, color:MUTED, fontWeight:"bold" },
  playersTxtOn:   { color:"#8B0000" },
  prevHpTxt:      { fontSize:17, color:MUTED },
  addBtn:         { backgroundColor:ACCENT, paddingHorizontal:25, paddingVertical:13, borderRadius:6, marginLeft:"auto" },
  quickAddBtn:    { borderRadius:6, width:48, marginLeft:4, justifyContent:"center", alignItems:"center", alignSelf:"stretch" },
  quickAddBoss:   { borderRadius:6, width:100, marginLeft:4, justifyContent:"center", alignItems:"center", alignSelf:"stretch", backgroundColor:"#8B0000", borderColor:"#6B0000", borderWidth:1.5 },
  quickAddTxt:    { fontSize:22, fontWeight:"bold" },
  addBtnTxt:      { color:"#FFF8E8", fontSize:20, fontWeight:"bold" },
  scroll:         { flex:1, backgroundColor:BG },
  scrollInner:    { padding:12 },
  empty:          { alignItems:"center", paddingVertical:50 },
  group:          { marginBottom:20 },
  carousel:       { paddingBottom:8, paddingRight:4 },
  groupHeader:    { flexDirection:"row", alignItems:"center", marginBottom:8 },
  groupTitle:     { fontSize:15, fontWeight:"bold", color:TEXT, marginRight:6 },
  groupBadge:     { borderWidth:1, borderRadius:4, paddingHorizontal:6, paddingVertical:2, marginRight:4 },
  groupLine:      { flex:1, height:1, backgroundColor:BORDER, marginLeft:4 },
  card:           { backgroundColor:CARD_BG, borderWidth:2, borderRadius:10, overflow:"hidden", marginRight:12, elevation:3, shadowColor:"#000", shadowOffset:{width:0,height:2}, shadowRadius:4, shadowOpacity:0.15 },
  // ── Card header ──
  cardHead:       { paddingHorizontal:8, paddingVertical:6, borderBottomWidth:1, borderBottomColor:BORDER, flexDirection:"row", alignItems:"center", gap:0 },
  cardStatCol:    { flexDirection:"column", justifyContent:"center", alignItems:"flex-start", marginLeft:8, gap:3 },
  cardStatRow:    { flexDirection:"row", alignItems:"center", gap:3 },
  cardStatImg:    { width:16, height:16 },
  cardStatEmoji:  { fontSize:14, lineHeight:16 },
  cardStatVal:    { fontSize:12, fontWeight:"bold", color:TEXT, lineHeight:14 },
  cardSkillCol:   { flexDirection:"column", justifyContent:"center", alignItems:"flex-start", marginLeft:8, gap:3 },
  cardSkillImg:   { width:16, height:16 },
  cardImmuneCol:  { flexDirection:"row", flexWrap:"wrap", alignItems:"center", marginLeft:4, gap:2, maxWidth:44 },
  cardImmuneItem: { position:"relative", width:20, height:20 },
  cardImmuneImg:  { width:20, height:20, opacity:0.4 },
  cardImmuneCross:{ position:"absolute", top:-3, right:-3, width:11, height:11, borderRadius:6,
                    backgroundColor:"#CC2222", alignItems:"center", justifyContent:"center" },
  cardImmuneCrossTxt:{ fontSize:7, color:"#fff", fontWeight:"bold", lineHeight:9 },
  iconCircle:     { width:44, height:44, borderRadius:22, borderWidth:2, justifyContent:"center", alignItems:"center", flexShrink:0, overflow:"hidden" },
  monsterImg:     { width:44, height:44, borderRadius:22 },
  cardTitle:      { fontSize:13, fontWeight:"bold", flexWrap:"wrap" },
  // Token rectangular
  tokenRect:      { width:36, height:36, borderRadius:8, borderWidth:2, justifyContent:"center", alignItems:"center", marginLeft:4, flexShrink:0 },
  tokenTxt:       { fontWeight:"bold", fontSize:15 },
  // ── HP ──
  hpSec:          { paddingHorizontal:8, paddingTop:7, paddingBottom:5 },
  hpRow:          { flexDirection:"row", alignItems:"center", justifyContent:"space-between", marginBottom:4, gap:6 },
  hpLbl:          { fontSize:10, color:MUTED, letterSpacing:1, fontWeight:"bold" },
  hpPills:        { flexDirection:"row", gap:4 },
  hpVal:          { fontSize:20, fontWeight:"bold" },
  hpMax:          { fontSize:11, color:"#C4B090", fontWeight:"normal" },
  hpBarOut:       { height:7, borderRadius:4, overflow:"hidden", backgroundColor:"#EDE4D0", borderWidth:1, borderColor:BORDER },
  hpBarIn:        { height:"100%", borderRadius:4 },
  // Escudo pills
  pillBase:       { flexDirection:"row", alignItems:"center", backgroundColor:"#DCE9F5", borderRadius:11, paddingHorizontal:7, paddingVertical:3, borderWidth:1, borderColor:"#A8C0D8" },
  pillBaseTxt:    { fontSize:12, fontWeight:"bold", color:"#1F618D" },
  pillTemp:       { flexDirection:"row", alignItems:"center", backgroundColor:"#FFF8D6", borderRadius:10, paddingHorizontal:7, paddingVertical:2, borderWidth:1 },
  pillTempTxt:    { fontSize:10, fontWeight:"bold" },
  // ── Daño ──
  dmgSec:         { paddingHorizontal:6, paddingVertical:7, borderTopWidth:1, borderTopColor:BORDER, backgroundColor:"#FBF7EE" },
  dmgLbl:         { fontSize:10, color:MUTED, letterSpacing:1, fontWeight:"bold", marginBottom:5 },
  dmgRow:         { flexDirection:"row", alignItems:"center", marginBottom:6, gap:4, paddingHorizontal:4 },
  dmgBtnSm:       { flex:1, height:34, borderRadius:5, backgroundColor:"#EDE4D0", borderWidth:1, borderColor:BORDER, justifyContent:"center", alignItems:"center" },
  dmgBtnLg:       { width:38, height:38, borderRadius:6, backgroundColor:"#EDE4D0", borderWidth:1, borderColor:BORDER, justifyContent:"center", alignItems:"center" },
  dmgBtnLgTxt:    { fontSize:15, fontWeight:"bold", color:TEXT },
  dmgBtnTxt:      { fontSize:13, fontWeight:"bold", color:TEXT },
  dmgBox:         { width:52, height:52, borderRadius:6, paddingVertical:4, alignItems:"center", justifyContent:"center", borderWidth:1 },
  dmgBoxOn:       { backgroundColor:"#FFF3CC", borderColor:"#D4A800" },
  dmgBoxOff:      { backgroundColor:"#F0EBE0", borderColor:BORDER },
  dmgBoxBlocked:  { backgroundColor:"#E8F0FF", borderColor:"#3070C8" },
  dmgVal:         { fontSize:16, fontWeight:"bold" },
  dmgValOn:       { color:"#7A5C00" },
  dmgValOff:      { color:"#C4B090" },
  dmgValBlocked:  { color:"#3070C8" },
  dmgInfo:        { fontSize:10, marginTop:1, textAlign:"center" },
  applyBtn:       { paddingHorizontal:4, height:32, borderRadius:6, justifyContent:"center", alignItems:"center", backgroundColor:"#CC2222", marginRight:2 },
  applyBtnOff:    { backgroundColor:"#993333" },
  applyTxt:       { color:"#fff", fontWeight:"bold", fontSize:12 },
  // Curar + Trampa en fila
  healTrapRow:    { flexDirection:"row", gap:5 },
  healBtn:        { flex:1, borderRadius:6, backgroundColor:"#22A355", justifyContent:"center", alignItems:"center", height:36, elevation:2, minWidth:0 },
  healTxt:        { color:"#fff", fontWeight:"bold", fontSize:12, textAlign:"center" },
  healStatusImg:  { width:16, height:16 },
  trapBtn:        { width:56, borderRadius:6, backgroundColor:"#7A5C00", justifyContent:"center", alignItems:"center", height:36, elevation:1 },
  trapTxt:        { color:"#FFF8E8", fontWeight:"bold", fontSize:11 },
  actionBtn:      { flex:1, borderRadius:6, backgroundColor:"#7A5C00", justifyContent:"center", alignItems:"center", height:40, elevation:2, flexDirection:"row", gap:2 },
  actionBtnSm:    { width:46, borderRadius:6, backgroundColor:"#7A5C00", justifyContent:"center", alignItems:"center", height:40, elevation:1, flexDirection:"row", gap:2 },
  actionBtnTxt:   { color:"#fff", fontWeight:"bold", fontSize:13 },
  actionBtnSub:   { color:"#FFF8E8", fontWeight:"bold", fontSize:13 },
  actionBtnImg:   { width:16, height:16 },
  // ── Escudo + Perforación fila dual ──
  statDualRow:    { flexDirection:"row", backgroundColor:"#F8F3E8", borderTopWidth:1, borderTopColor:BORDER, justifyContent:"center" },
  statCol:        { flex:1, paddingHorizontal:6, paddingVertical:6 },
  statColLbl:     { fontSize:11, color:MUTED, fontWeight:"bold", marginBottom:4, textAlign:"center" },
  statColCtrl:    { flexDirection:"row", alignItems:"center", gap:4, flex:1 },
  statDivider:    { width:1, backgroundColor:BORDER, marginVertical:6 },
  statVal:        { minWidth:18, textAlign:"center", fontWeight:"bold", fontSize:17, color:TEXT },
  btnSm:          { flex:1, height:34, borderRadius:5, borderWidth:1, borderColor:BORDER, backgroundColor:"#EDE4D0", justifyContent:"center", alignItems:"center" },
  btnSmTxt:       { fontSize:17, fontWeight:"bold", color:TEXT },
  stSec:          { paddingHorizontal:8, paddingTop:7, paddingBottom:10, borderTopWidth:1, borderTopColor:BORDER },
  stLbl:          { fontSize:10, color:MUTED, letterSpacing:1, fontWeight:"bold", marginBottom:5, textAlign:"center" },
  stRow:          { flexDirection:"row", flexWrap:"wrap", justifyContent:"center" },
  stBtn:          { flex:1, backgroundColor:"#F0EBE0", borderWidth:1, borderColor:BORDER, borderRadius:6, paddingVertical:5, marginHorizontal:2, marginBottom:3, opacity:0.45, justifyContent:"center", alignItems:"center" },
  stBtnImmune:    { opacity:1, backgroundColor:"#F0E8E8", borderColor:"#CC4444", position:"relative" },
  immuneBadge:    { position:"absolute", top:-4, right:-4, width:13, height:13, borderRadius:7,
                    backgroundColor:"#CC2222", alignItems:"center", justifyContent:"center" },
  immuneTxt:      { fontSize:7, color:"#fff", fontWeight:"bold", lineHeight:9 },
  stImg:          { width:24, height:24 },
  footer:         { backgroundColor:BG, borderTopWidth:1, borderTopColor:BORDER, paddingVertical:6, paddingHorizontal:4 },
  footerTxt:      { fontSize:10, color:"#C4B090", textAlign:"center" },
  // ── MODO VIZ (visualización / espectador) ──
  vzHpSec:        { paddingHorizontal:12, paddingTop:10, paddingBottom:10, borderTopWidth:1, borderTopColor:BORDER, backgroundColor:"#FBF7EC" },
  vzHpRow:        { flexDirection:"row", alignItems:"baseline", justifyContent:"space-between", marginBottom:8 },
  vzHpLbl:        { fontSize:13, color:MUTED, fontWeight:"500" },
  vzHpVal:        { fontSize:34, fontWeight:"bold", lineHeight:38 },
  vzHpMax:        { fontSize:18, color:MUTED, fontWeight:"400" },
  vzHpBarOut:     { height:14, backgroundColor:"#EDE4D0", borderRadius:7, overflow:"hidden" },
  vzHpBarIn:      { height:"100%", borderRadius:7 },
  vzDefRow:       { flexDirection:"row", paddingHorizontal:12, paddingVertical:10, gap:10, borderTopWidth:1, borderTopColor:BORDER },
  vzDefItem:      { flex:1, flexDirection:"column", alignItems:"center", justifyContent:"center", gap:2, backgroundColor:"#F5EFE0", paddingVertical:8, paddingHorizontal:6, borderRadius:8 },
  vzDefItemOff:   { opacity:0.35 },
  vzDefIcon:      { width:24, height:24 },
  vzDefVal:       { fontSize:24, fontWeight:"bold", color:TEXT, minWidth:20, textAlign:"center" },
  vzDefLbl:       { fontSize:11, color:MUTED, fontWeight:"500" },
  vzStSec:        { paddingHorizontal:8, paddingTop:8, paddingBottom:10, borderTopWidth:1, borderTopColor:BORDER, justifyContent:"center" },
  vzStRow:        { flexDirection:"row", justifyContent:"space-between" },
  vzStBtn:        { width:34, height:34, borderWidth:1.5, borderRadius:7, justifyContent:"center", alignItems:"center" },
  vzStImg:        { width:22, height:22 },
  overlay:        { position:"absolute", top:0, left:0, right:0, bottom:0, backgroundColor:"rgba(0,0,0,0.55)", justifyContent:"center", alignItems:"center", zIndex:999 },
  popup:          { backgroundColor:CARD_BG, borderRadius:14, padding:22, width:"80%", borderWidth:2, borderColor:"#8B0000", shadowColor:"#000", shadowOffset:{width:0,height:4}, shadowRadius:12, shadowOpacity:0.4, elevation:10 },
  popupTitle:     { fontSize:18, fontWeight:"bold", color:"#8B0000", marginBottom:4 },
  popupSub:       { fontSize:12, color:MUTED, marginBottom:12 },
  popupRow:       { flexDirection:"row", alignItems:"center", marginBottom:8, width:"100%" },
  popupIcon:      { fontSize:20, marginRight:8 },
  popupImgWrap:   { width:36, height:36, borderRadius:18, overflow:"hidden", borderWidth:1.5, marginRight:10, justifyContent:"center", alignItems:"center", backgroundColor:"#F0E6D0" },
  popupImg:       { width:36, height:36, borderRadius:18 },
  popupVariantTag:{ borderRadius:4, paddingHorizontal:6, paddingVertical:2, borderWidth:1, marginRight:6 },
  popupVariantTxt:{ fontSize:10, fontWeight:"bold" },
  popupName:      { fontSize:13, fontWeight:"bold", color:TEXT, flex:1, marginRight:6 },
  popupNumBadge:  { backgroundColor:"#FFE0E0", borderRadius:6, paddingHorizontal:8, paddingVertical:2, borderWidth:1, borderColor:"#8B0000" },
  popupNum:       { fontSize:13, fontWeight:"bold", color:"#8B0000" },
  popupBtn:       { marginTop:14, backgroundColor:"#8B0000", borderRadius:8, paddingHorizontal:28, paddingVertical:10 },
  popupBtnTxt:    { color:"#fff", fontWeight:"bold", fontSize:14 },
  // Back button header
  backBtnHdr:     { paddingHorizontal:16, paddingVertical:12, justifyContent:"center", alignItems:"center" },
  backIconHdr:    { color:"#F5DEB3", fontSize:20, fontWeight:"bold", lineHeight:20, includeFontPadding:false },
  // Nivel badge
  lvlBadge:       { flexDirection:"row", alignItems:"center", backgroundColor:"#5A2D0A", borderRadius:8,
                    paddingHorizontal:10, paddingVertical:5, borderWidth:1, borderColor:"#A0845C", gap:4 },
  lvlBadgeLbl:    { fontSize:10, color:"#A0845C", fontWeight:"bold", letterSpacing:1 },
  lvlBadgeNum:    { fontSize:18, color:"#F5DEB3", fontWeight:"bold", lineHeight:22 },
  // Modal nivel
  lvlGrid:        { flexDirection:"row", flexWrap:"wrap", padding:16, gap:10, justifyContent:"center" },
  lvlGridBtn:     { width:64, height:64, borderRadius:12, borderWidth:2, borderColor:BORDER,
                    backgroundColor:"#EDE4D0", justifyContent:"center", alignItems:"center" },
  lvlGridBtnOn:   { backgroundColor:ACCENT, borderColor:"#F5DEB3" },
  lvlGridNum:     { fontSize:24, fontWeight:"bold", color:MUTED },
  lvlGridNumOn:   { color:"#FFF8E8" },
  lvlHint:        { fontSize:11, color:MUTED, textAlign:"center", paddingHorizontal:16, paddingBottom:16 },
});